name: Christopher J. Campo
description:
meta_description: "C.J. Campo"

highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.ccampo.me'
google_analytics: 'UA-61649602-1'

# Details for the RSS feed generator
url:            'https://www.ccampo.me'
enforce_ssl:    'www.ccampo.me'
author:         'Christopher J. Campo'

gems:
  - jekyll-paginate
  - jekyll-gist
