name: Christopher J. Campo
description:
meta_description: "C.J. Campo"

markdown: redcarpet
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://ccampo.me'
google_analytics: 'UA-61649602-1'

# Details for the RSS feed generator
url:            'https://ccampo.me'
enforce_ssl:    'ccampo.me'
author:         'Christopher J. Campo'
